name: check build gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/gradle-build-action@v3.5.0
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build