name: check build gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: zulu
          java-version: 17
      - uses: gradle/gradle-build-action@v3.5.0
      - name: check Spotless
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/gradle-build-action@v3.5.0
      - name: set build
        run: chmod +x ./gradlew

      - name: Android build
        run: ./gradlew build

    build:
      runs-on: macOS-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: 21

        - name: iOS build
          run: cd iosApp && xcodebuild -scheme iosApp -configuration Debug -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' CODE_SIGNING_ALLOWED='NO'